reflectsongs/urls.py
"""reflectsongs URL Configuration

"""
from django.urls import path
from django.views.generic import TemplateView

from reflectsongs.views import (DownloadResource, HomeView, Search,
                                SetlistList, SetlistView, SiteList, SiteView,
                                SongList, SongPresentation, SongView, Words, Radio)

urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name="reflectsongs/robots.txt")),

    path('', HomeView.as_view(), name='index'),

    # Setlists
    path('setlists/<pk>/', SetlistView.as_view(), name='setlist-view'),
    path('setlists/', SetlistList.as_view(), name='setlist-list'),

    # Songs
    path('songs/<slug:song_slug>/', SongView.as_view(), name='song-view'),
    path('songs/<slug:song_slug>/show', SongPresentation.as_view(),
         name='song-show'),
    path('songs/', SongList.as_view(), name='song-list'),

    # Downloads
    path('download/<pk>/', DownloadResource.as_view(), name='download'),

    # Sites
    path('sites/<slug:slug>/', SiteView.as_view(), name='site-view'),
    path('sites/', SiteList.as_view(), name='site-list'),

    # Search
    path('search', Search.as_view(), name='search'),

    # Stats
    path('words', Words.as_view(), name='words'),

    # Radio video player
    path('radio', Radio.as_view(), name='radio'),


]

reflectworship/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from reflectsongs import urls as reflect_urls

urlpatterns = [
    path('', include(reflect_urls)),
    path('admin/', admin.site.urls),
]

reflectsongs/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils import formats, timezone
from django.utils.translation import gettext as _

from dateutil.relativedelta import relativedelta
from reflectsongs.utils import yt_embed
from reflectsongs.utils import unique_slugify, url_to_link, yt_image

SONGSELECT_BASE_URL = 'https://songselect.ccli.com/Songs/'


class ModelBase(models.Model):
    """ Common model config """
    class Meta:
        abstract = True

    # UUIDs as primary key
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)


class Site(ModelBase):
    """
    A single church site or location
    """
    def __str__(self):
        return self.name

    name = models.CharField(
        max_length=200,
        unique=True,
    )

    slug = models.SlugField(
        null=True
    )

    def recent_setlist(self):
        return self.setlists.first()


class Theme(ModelBase):
    """
    A theme/category
    """
    def __str__(self):
        return self.name

    name = models.CharField(
        max_length=200,
    )

    slug = models.CharField(
        max_length=200,
        blank=True,
    )

    def save(self, **kwargs):
        unique_slugify(self, self.name)
        super().save(**kwargs)


class Song(ModelBase):
    """
    A worship song
    """
    class Meta:
        ordering = (
            'title',
        )

    def __str__(self):
        return self.title

    title = models.CharField(
        max_length=200,
    )

    slug = models.CharField(
        max_length=200,
        blank=True,
    )

    authors = models.CharField(
        max_length=200,
    )

    copyright_year = models.IntegerField(
        blank=True,
        null=True,
    )

    copyright_info = models.CharField(
        max_length=300,
        blank=True,
        null=True,
    )

    themes = models.ManyToManyField(
        Theme,
        related_name='songs',
        blank=True,
    )

    ccli_number = models.CharField(
        _('CCLI Number'),
        max_length=200,
        blank=True,
        null=True,
    )

    featured = models.BooleanField(
        help_text=(
            'Featured songs appear at the top of the homepage'
            '*New song* listings'
            ),
        default=False,
    )

    all_age = models.BooleanField(
        help_text=(
            'This song is recommended for all-age worship'
            ),
        default=False,
    )

    youtube_url = models.URLField(
        blank=True,
        null=True,
    )

    worshiptogether_url = models.URLField(
        blank=True,
        null=True,
    )

    lyrics = models.TextField(
        blank=True,
        null=True,
    )

    last_sync = models.DateTimeField(
        _('Last Sync'),
        null=True,
        blank=True,
    )

    @property
    def embed_code(self):
        if self.youtube_url:
            return yt_embed(self.youtube_url)

    @property
    def badges(self):
        badges = []
        if self.all_age:
            badges.append('all-age')
        if self.featured:
            badges.append('featured')
        return badges

    @property
    def last_played(self):
        if self.setlists.count():
            return self.setlists.order_by('-date').first()

    def last_played_site(self, site):
        setlists = self.setlists.filter(site=site)
        if setlists.count():
            return setlists.order_by('-date').first()

    def recent_setlists(self, months=6, site=None):
        now = timezone.now()
        recent = self.setlists.filter(date__gt=now-relativedelta(months=months))
        if site:
            recent = recent.filter(site=site)
        return recent

    @property
    def first_played(self):
        if self.setlists.count():
            return self.setlists.order_by('-date').last()

    @property
    def songselect_url(self):
        if self.ccli_number:
            return SONGSELECT_BASE_URL + self.ccli_number
        else:
            return ''

    @property
    def songselect_link(self):
        if self.ccli_number:
            return url_to_link(self.songselect_url)
        else:
            return ''
    songselect_link.fget.short_description = _('SongSelect Link')

    @property
    def photo(self):
        if self.youtube_url:
            return yt_image(self.youtube_url)

    def get_absolute_url(self):
        return reverse('song-view', args=(self.slug, ))

    @property
    def youtube_url_nocookie(self):
        if self.youtube_url:
            return self.youtube_url.replace('youtube.com', 'youtube-nocookie.com').strip()

    def save(self, **kwargs):
        unique_slugify(self, self.title)
        super().save(**kwargs)


class ChordResource(ModelBase):
    """ Represents a chord download (sheet music) """

    song = models.ForeignKey(
        Song,
        on_delete=models.CASCADE,
        related_name='downloads',
    )
    resource_type = models.CharField(
        max_length=200,
        choices=(
            ('pdf', 'PDF'),
            ('chordpro', 'ChordPro'),
        ),
    )
    song_key = models.CharField(
        max_length=5,
        null=True,
        blank=True,
        choices=(
            ('aflat', 'Ab'),
            ('a', 'A'),
            ('bflat', 'Bb'),
            ('b', 'B'),
            ('c', 'C'),
            ('csharp', 'C'),
            ('dflat', 'Db'),
            ('d', 'D'),
            ('eflat', 'Eb'),
            ('e', 'E'),
            ('f', 'F'),
            ('fsharp', 'F#'),
            ('gflat', 'Gb'),
            ('g', 'G'),
        ),
    )
    attachment = models.FileField(
        upload_to='chordresources',
    )


class Setlist(ModelBase):
    """
    A set of songs
    """
    class Meta:
        ordering = ('-date', )
        unique_together = (
            ('date', 'name', 'site', ),
        )

    def __str__(self):
        value = '{}: {}'.format(
            str(self.date),
            self.site,
        )
        if self.name:
            value += ' ({})'.format(self.name)
        return value

    @property
    def friendly_name(self):
        date = formats.date_format(self.date, 'DATE_FORMAT')
        return f"{date}: {self.site} ({self.short_name})"

    @property
    def short_name(self):
        short = self.name.replace(self.site.name, '')
        return short.strip()

    date = models.DateField()
    name = models.CharField(
        max_length=200,
        blank=True,
        null=True,
    )
    site = models.ForeignKey(
        Site,
        on_delete=models.CASCADE,
        related_name='setlists',
    )

    songs = models.ManyToManyField(
        Song,
        related_name='setlists',
        blank=True,
    )

    source = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    import_date = models.DateTimeField(
        blank=True,
        null=True,
    )

    pp_uid = models.CharField(
        "ProPresenter ID",
        max_length=200,
        blank=True,
        null=True,
        unique=True,
    )

    def get_absolute_url(self):
        return reverse('setlist-view', args=(self.id, ))

reflectsongs/templates/reflectsongs/base.html
{% load static %}
{% load reflect_extras %}
<!doctype html>
<html lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta property="og:site_name" content="Reflect" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="The City Church Worship Database" />
    <meta property="og:description" content="The City Church Worship Database" />
    <meta property="og:image" content="{% root_url %}{% static 'reflect/reflect-banner-space.jpg' %}" />

      <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <link rel="stylesheet" href="{% static 'reflect/styles.css' %}?v=20190724">

      <title>{% block title %}{% endblock %} | Reflect</title>
    {% block head %}
    {% endblock %}
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{% static 'reflect/reflect-logo.png' %}" width="150" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link {% navactive request 'setlist-list' %}"
               href="{% url 'setlist-list' %}">Setlists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% navactive request 'song-list' %}"
               href="{% url 'song-list' %}">Songs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% navactive request 'site-list' %}"
               href="{% url 'site-list' %}">Sites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% navactive request 'radio' %}"
               href="{% url 'radio' %}">Radio</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}">
          <input class="form-control mr-sm-2" type="search"
                 accesskey="/"
                 name="q"
                 value="{{ request.GET.q }}"
                 placeholder="Song Search" aria-label="Search" />
          <button class="btn btn-outline-secondary my-2 my-sm-0"
                  type="submit">Go
          </button>
        </form>
      </div>
      </div>
    </nav>

    <div id="content" class="container">

      {% block content %}
      {% endblock %}

    </div>

    <div id="footer" class="container text-right">
      Reflect: The Worship Database
      <br />
      &copy; 2019 <a href="https://www.citychurch.org.uk">City Church Bristol</a>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Charts JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
    <script src="{% static 'reflect/mypies.js' %}"></script>

    <!-- Privacy friendly stats via GoatCounter -->
    <script>
	    (function() {
		  // Only load on production environment.
		  if (window.location.host !== 'reflect.citychurch.org.uk') {
			return;
      }

		  window.counter = 'https://reflectworship.goatcounter.com/count'

		  var script = document.createElement('script');
		  script.async = 1;
		  script.src = '//gc.zgo.at/count.js';
		  var ins = document.getElementsByTagName('script')[0];
		  ins.parentNode.insertBefore(script, ins)
	    })();
    </script>
  </body>
</html>

reflectsongs/templates/reflectsongs/index.html
{% extends 'reflectsongs/base.html' %}

{% block title %}Home{% endblock %}
{% block content %}

<div class="card-deck">

  <div class="card">
    <h5 class="card-header">Top Songs</h5>
    <div class="card-body">
      <p>
        Most frequently played songs in the last 6 months
      </p>
      {% if topsongs.0.photo %}
      <a href="{% url 'song-view' topsongs.0.slug %}">
        <img src="{{ topsongs.0.photo }}" class="img-fluid" />
      </a>
      {% endif %}
      <table class="table table-striped">
        <thead>
          <th>Song</th>
          <th>Plays</th>
        </thead>
        {% for song in topsongs %}
        <tr>
          <td>
            <a href="{% url 'song-view' song.slug %}">{{ song }}</a>
            {% if song.authors %}
            <br />
            <small>{{ song.authors }}</small>
            {% endif %}
          </td>
          <td>
            {{ song.setlist_count }}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <div class="card">
    <h5 class="card-header">New Songs</h5>
    <div class="card-body">
      <p>
        Songs most recently introduced
      </p>
      {% if newsongs.0.photo %}
      <a href="{% url 'song-view' newsongs.0.slug %}">
        <img src="{{ newsongs.0.photo }}" class="img-fluid" />
      </a>
      {% endif %}
      <table class="table table-striped">
        <thead>
          <th>Song</th>
          <th width="30%">First Played</th>
        </thead>
        {% for song in newsongs %}
        <tr>
          <td>
            <a href="{% url 'song-view' song.slug %}">{{ song }}</a>
            {% if song.authors %}
            <br />
            <small>{{ song.authors }}</small>
            {% endif %}
          </td>
          <td>
            {% if song.featured %}
            <span class="badge badge-pill badge-success">featured</span>
            <br />
            {% endif %}
            {{ song.first_played.date }}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

<div class="card-deck mt-3">
  {% for site in sites %}
  <div class="card">
    <h5 class="card-header">
      <a href="{% url 'site-view' site.slug %}">
        {{ site.name }}
      </a>
    </h5>
    <div class="card-body">
      <p>
        <a href="{% url 'setlist-view' site.recent_setlist.id %}">
          <em>Setlist {{ site.recent_setlist.friendly_name }}</em>
        </a>
      </p>
      <table class="table table-striped">
        {% for song in site.recent_setlist.songs.all %}
        <tr>
          <td>
            <a href="{% url 'song-view' song.slug %}">{{ song }}</a>
            {% if song.authors %}
            <br />
            <small>{{ song.authors }}</small>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock %}

reflectsongs/templates/reflectsongs/radio.html
{% extends 'reflectsongs/base.html' %}

{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.5/video.min.js"
  integrity="sha512-HwmeTRPtX4IwZhPJINKNQQ/szpRFWGFk9Cv5JTLTEENcM6Kq6VD/5GKRSZJ37CHzYaS8dK1CfsNk9MXLDm/dLQ==" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-youtube/2.6.1/Youtube.min.js" integrity="sha512-mF+XuiEvJq707N/B9Fm/fI2wgMcWuFLsoztIp0UzEKgHCZgczbYpO2+Vq2TEi0LmE4crVj2r8AYru7X5QjVotw==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/videojs-playlist@4.3.1/dist/videojs-playlist.min.js" integrity="sha256-9SaTQgEH5mVWnqixYTM3cjyN8zbUTx/UmldDVFYLU70=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.5/video-js.min.css" integrity="sha512-+krGgE9EwStC6GBtdEVdolP3uGa4ZiPGLxq6S4lY4R2eLK0/+1EJND+7llLQ+TBpt4/6vu4RWP6g8r60/JJNHQ==" crossorigin="anonymous" />

{% endblock %}

{% block title %}Radio{% endblock %}
{% block content %}

<div class="row">
  <div class="col-sm-12 col-md-6">

    <h1>
      Reflect Radio
    </h1>

    <div id="player" class="card mb-3">
      <div class="card-body">

        <div id="video">
          <video id="playlist" class="video-js vjs-fluid"
                  playsinline
                  controls
                  data-setup='{}'>
        </div>
        <div class="buttons mt-3">
          <a class="btn btn-primary btn-sm prev float-left" href="#">prev</a>
          <a class="btn btn-primary btn-sm next float-right" href="#">next</a>
        </div>
    </div>
  </div>

  </div>
  <div class="col-sm-12 col-md-6">
    <p>
      A random playlist of the
      <a href="{% url 'song-list' %}?range=12m">
      most popular songs</a> sung over the past 12 months.
    </p>
    <ul class="list-group mt-3">
      {% for song in songs %}
      <li class="list-group-item song">
        <div class="buttons float-right">
        <a class="btn btn-light btn-sm play" href="#">play</a>
        <a class="btn btn-light btn-sm details" href="{% url 'song-view' song.slug %}" target="_blank">details</a>
        </div>
          <b>{{ song }}</b>
          {% if song.authors %}<br /><small>{{ song.authors }}</small>{% endif %}
          <br />
        </li>
        {% endfor %}
    </ul>
  </div>
</div>

<script>
var player = videojs(
  'playlist',
  { nativeControlsForTouch: true, youtube: {enablePrivacyEnhancedMode: true }}
);
var songs = [];
{% for song in songs %}
songs.push({
  sources: [{
    src: '{{ song.youtube_url_nocookie }}',
    type: 'video/youtube'
  }]
});
{% endfor %}

player.playlist(songs);

// Play through the playlist automatically.
player.playlist.autoadvance(0);

// Set up individual play buttons
$('li.song a.play').each(function(ind, item) {
  $(item).on('click', function() {
    player.playlist.currentItem(ind);
    player.play();
    return false;
  });
});

// next/prev controls
$('#player a.next').on('click', function() {
  player.playlist.next();
  player.play();
  return false;
});
$('#player a.prev').on('click', function() {
  player.playlist.previous();
  player.play();
  return false;
});

// Highlight active item
player.on('playlistitem', function(event, item) {
  var id = item.playlistItemId_;
  $('li.song').removeClass('active');
  $('li.song:nth-child(' + id + ')').addClass('active');
});

</script>


{% endblock %}

reflectsongs/templates/reflectsongs/setlist_detail.html
{% extends 'reflectsongs/base.html' %}

{% block content %}
<h1>{% block title %}{{ setlist.friendly_name }}{% endblock %}</h1>

  <div class="card mb-3">
    <div class="card-body">
      <table class="table table-striped">
        {% for song in setlist.songs.all  %}
        <tr>
          <td>
            {% if song.photo %}
            <img src="{{ song.photo }}" class="rounded float-right d-none d-md-block thumb" />
            {% endif %}
            <a href="{% url 'song-view' song.slug %}">{{ song }}</a>
            {% if song.authors %}
            <br />
            <small>{{ song.authors }}</small>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  {% if request.user.is_staff %}
  <p>
    <a class="btn btn-outline-primary" href="{% url 'admin:reflectsongs_setlist_change' setlist.id %}">Edit</a>
  </p>
{% endif %}

{% endblock %}

reflectsongs/templates/reflectsongs/setlist_list.html
{% extends 'reflectsongs/base.html' %}
{% load reflect_extras %}

{% block content %}

<h1>{% block title %}{{ title }}{% endblock %}</h1>

<p>
  {%if filter_song %}
  Including: <a href="{% url 'song-view' filter_song.slug %}">{{ filter_song }}</a>
  <br />
  {%endif%}
  {{ page_obj.paginator.count }} results
</p>

<ul class="list-group mt-3">
  {% for setlist in setlists %}
  <li class="list-group-item">
    <a href="{% url 'setlist-view' setlist.id %}">{{ setlist.friendly_name }}</a>
    <small>- <b>{{ setlist.songs.count }} songs</b></small>
    <br />
    <small>{{ setlist.songs.all|join:", " }}</small>
  </li>
  {% endfor %}
</ul>

<nav aria-label="Batch avigation">
  <ul class="pagination mt-3">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    <li class="page-item disabled">
      <a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}

reflectsongs/templates/reflectsongs/site_list.html
{% extends 'reflectsongs/base.html' %}

{% block content %}

<h1>{% block title %}Sites{% endblock %}</h1>

<ul class="list-group mt-3">
  {% for site in sites %}
  <li class="list-group-item">
    <a href="{% url 'site-view' site.slug %}">{{ site.name }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

reflectsongs/templates/reflectsongs/song.html
{% extends 'reflectsongs/base.html' %}

{% block content %}
<div class="row">
  <div class="col-sm-12 col-md-6">

    <h1>
      {% block title %}{{ song.title }}{% endblock %}
    </h1>

    {% if song.badges %}
    <p>
      {% for badge in song.badges %}
      <span class="badge badge-pill badge-success">{{ badge }}</span>
      {% endfor %}
    </p>
    {% endif %}

    <dl class="row">
      <dt class="col-sm-3">Authors</dt>
      <dd class="col-sm-9">
        {% if song.authors %}
        {{ song.authors }}
        {% else %}
        <em>Unknown</em>
        {% endif %}
      </dd>

      {% if song.themes.count %}
      <dt class="col-sm-3">Themes</dt>
      <dd class="col-sm-9">
        {% for theme in song.themes.all %}
        <a href="{% url 'search' %}?theme={{ theme.slug }}">{{ theme }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </dd>
      {% endif %}

      {% if song.copyright_year %}
      <dt class="col-sm-3">Copyright</dt>
      <dd class="col-sm-9">{{ song.copyright_year }}</dd>
      {% endif %}

      <dt class="col-sm-3">Plays</dt>
      <dd class="col-sm-9">
        All time: <b><a href="{% url 'setlist-list' %}?song={{song.slug}}">
            {{ song.setlists.count }}
        </a></b>
        <br />
        Last 6 months: <b>{{ song.recent_setlists.count }}</b>
      </dd>

      <dt class="col-sm-3">Last played</dt>
      <dd class="col-sm-9">
        {% for lp in last_played_sites %}
        {{ lp.site }}:
        {% if lp.last_played %}
        <a href="{% url 'setlist-view' lp.last_played.id %}">
          {{ lp.last_played.date }}
        </a>
        {% else %}
        &mdash;
        {% endif %}
        <br />
        {% endfor %}
      </dd>
    </dl>
    <p>
      {% if song.songselect_url %}
      <a class="btn btn-primary"
         href="{{ song.songselect_url }}"
         role="button">SongSelect</a>
      {% endif %}
      {% if song.worshiptogether_url %}
      <a class="btn btn-success"
         href="{{ song.worshiptogether_url }}"
         role="button">Worship Together</a>
      {% endif %}
    </p>

  </div>

  <div class="col-sm-12 col-md-6">

    {% if song.youtube_url %}
    <div class="card mb-3" style="max-width: 500px">
      <h5 class="card-header">Video</h5>
      <div class="card-body">
        <div class='embed-container'>
          {{ embed_code }}
        </div>
      </div>
    </div>
    {% endif %}

  </div>

</div>

<div class="row">

  <div class="col-sm-12 col-md-6">
  {% if song.lyrics %}
  <h4>Lyrics</h4>
  <p>
    <a href="{% url 'song-show' song.slug %}">&raquo; Presentation mode</a>
  </p>
    <p>
      {{ song.lyrics | linebreaks }}
    </p>
    {% if song.copyright_info %}
    <p>
      <em>{{ song.copyright_info }}</em>
    </p>
    {% endif %}
  {% endif %}
  </div>

  {% if downloads %}
  <div class="col-sm-12 col-md-6" id="song-downloads">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h4>Downloads</h4>
      </li>
      {% for download in downloads %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'download' download.id %}">
          Chords ({{ download.get_resource_type_display }})
        </a>
          {% if download.song_key %}
          <span class="badge badge-primary badge-pill">
            Key: {{ download.get_song_key_display }}
          </span>
          {% endif %}
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

</div>

{% if request.user.is_staff %}
<a class="btn btn-outline-primary" href="{% url 'admin:reflectsongs_song_change' song.id %}">Edit</a>
{% endif %}

{% endblock %}